project_name: VideoAutoencoder

RealEstate10K:
  name: RealEstate10K
  train_path: /home/airlab/SONY2022/VideoAutoencoder/dataset/train/
  test_path: /home/airlab/SONY2022/VideoAutoencoder/dataset/test/
  input_size: 256

BOP:
  name: BOP
  train_path: /home/airlab/storage/airlab/VideoAutoencoder/BOP/train/ycb2
  test_path: /home/airlab/storage/airlab/VideoAutoencoder/BOP/train/ycb2
  mask_path: /home/airlab/storage/airlab/bop_data/ycbv/test_video/obj_000002/mask
  cam_path: /home/airlab/storage/airlab/bop_data/ycbv/test_video/obj_000002/scene_camera.json
  input_size: 256

OWID:
  name: OWID
  train_path: /home/airlab/storage/airlab/VideoAutoencoder/BOP/train/ycb2
  test_path: /home/airlab/storage/airlab/VideoAutoencoder/BOP/train/ycb2
  mask_path: /home/airlab/storage/airlab/bop_data/ycbv/test_video/obj_000002/mask
  cam_path: /home/airlab/storage/airlab/bop_data/ycbv/test_video/obj_000002/scene_camera.json
  input_size: 256

Matterport3D_Preatrain:
  name: Matterport3D_Preatrain
  train_path: /home/zihang/developer/data/matterport/images/train_mini/
  test_path: null
  input_size: 256

Matterport3D:
  name: Matterport3D
  train_path: /home/zihang/developer/data/mp3d_train/
  test_path: /home/zihang/developer/data/mp3d_test/
  input_size: 256

Replica:
  name: Replica
  train_path: null
  test_path: /home/zihang/developer/data/replica_test/
  input_size: 256